app:
  datasource:
    jdbc-url: jdbc:postgresql://10.58.158.0:5433/postgres
    username: postgres
    password: dvulence00
    pool-size: 30

spring:
  flyway:
    baseline-on-migrate : true

server:
  port: 8081
